import { createBrowserRouter } from 'react-router';
import { Landing } from './pages/Landing';
import { SignUp } from './pages/auth/SignUp';
import { Login } from './pages/auth/Login';
import { Welcome } from './pages/onboarding/Welcome';
import { BirthDate } from './pages/onboarding/BirthDate';
import { BirthTime } from './pages/onboarding/BirthTime';
import { BirthTimeInfo } from './pages/onboarding/BirthTimeInfo';
import { BirthPlace } from './pages/onboarding/BirthPlace';
import { PeriodTracking } from './pages/onboarding/PeriodTracking';
import { PeriodRegularity } from './pages/onboarding/PeriodRegularity';
import { LastPeriodKnowledge } from './pages/onboarding/LastPeriodKnowledge';
import { LastPeriodDates } from './pages/onboarding/LastPeriodDates';
import { HormonalTracking } from './pages/onboarding/HormonalTracking';
import { Lifestyle } from './pages/onboarding/Lifestyle';
import { CurrentCity } from './pages/onboarding/CurrentCity';
import { Calculating } from './pages/onboarding/Calculating';
import { Paywall } from './pages/onboarding/Paywall';
import { Dashboard } from './pages/Dashboard';

export const router = createBrowserRouter([
  { path: '/',                                 Component: Landing },
  { path: '/signup',                           Component: SignUp },
  { path: '/login',                            Component: Login },
  { path: '/onboarding/welcome',               Component: Welcome },
  { path: '/onboarding/birth-date',            Component: BirthDate },
  { path: '/onboarding/birth-time',            Component: BirthTime },
  { path: '/onboarding/birth-time-info',       Component: BirthTimeInfo },
  { path: '/onboarding/birth-place',           Component: BirthPlace },
  { path: '/onboarding/period-tracking',       Component: PeriodTracking },
  { path: '/onboarding/period-regularity',     Component: PeriodRegularity },
  { path: '/onboarding/last-period-knowledge', Component: LastPeriodKnowledge },
  { path: '/onboarding/last-period-dates',     Component: LastPeriodDates },
  { path: '/onboarding/hormonal-tracking',     Component: HormonalTracking },
  { path: '/onboarding/lifestyle',             Component: Lifestyle },
  { path: '/onboarding/current-city',          Component: CurrentCity },
  { path: '/onboarding/calculating',           Component: Calculating },
  { path: '/onboarding/paywall',               Component: Paywall },
  { path: '/dashboard',                        Component: Dashboard },
]);